# Generated by Django 3.1.5 on 2023-01-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazilarmodel',
            old_name='duzenlenme_tarihi',
            new_name='guncellenme_tarihi',
        ),
        migrations.RenameField(
            model_name='yazilarmodel',
            old_name='tarih',
            new_name='olusturma_tarihi',
        ),
    ]
