# Generated by Django 3.1.5 on 2023-07-28 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0008_auto_20230728_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilarmodel',
            name='yazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazar', to=settings.AUTH_USER_MODEL),
        ),
    ]
