# Generated by Django 3.1.5 on 2023-08-07 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20230728_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=6, verbose_name='Gender')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)], verbose_name='Age')),
                ('estimated_salary', models.SmallIntegerField(verbose_name='EstimatedSalary')),
                ('purchased', models.BooleanField(verbose_name='Purchased')),
            ],
        ),
    ]
